apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: small-namespace
spec:
  labelSelector:
    matchLabels:
      size: small
  templates:  
    - objectTemplate: | 
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: {{ .Name }}-quota
          namespace: {{ .Name }}
        spec:
          hard: 
            requests.cpu: "10" 
            requests.memory: 10Gi 
            requests.ephemeral-storage: 10Gi
      excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas           
---              
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: medium-namespace
spec:
  labelSelector:
    matchLabels:
      size: medium
  templates:     
    - objectTemplate: | 
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: {{ .Name }}-quota
          namespace: {{ .Name }}
        spec:
          hard: 
            requests.cpu: "30" 
            requests.memory: 30Gi 
            requests.ephemeral-storage: 30Gi
      excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas            
---           
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: large-namespace
spec:
  labelSelector:
    matchLabels:
      size: large
  templates:     
    - objectTemplate: | 
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: {{ .Name }}-quota
          namespace: {{ .Name }}
        spec:
          hard: 
            requests.cpu: "50" 
            requests.memory: 50Gi 
            requests.ephemeral-storage: 50Gi
      excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas              