apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupConfig
metadata:
  name: tenant-gitops-service-accounts
spec:
  annotationSelector:
    matchLabels:
      devteam: "true"        
  templates:     
    - objectTemplate: |
        kind: ServiceAccount
        apiVersion: v1
        metadata:
          name: "{{ .Name }}-tenant-gitops"
          namespace: vault-admin
      excludedPaths:	
        - .spec.replicas	
        - .metadata	
        - .status
    - objectTemplate: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: "{{ .Name }}-tenant-gitops"
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: argocd-reader
        subjects:
        - kind: ServiceAccount
          name: "{{ .Name }}-tenant-gitops"
          namespace: vault-admin
      excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas                
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-reader
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["list","get","watch"]
       