apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupConfig
metadata:
  name: tenant-gitops-secret-engine-roles
spec:
  annotationSelector:
    matchLabels:
      devteam: "true"        
  templates:     
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: KubernetesSecretEngineRole
        metadata:
          name: "{{ .Name }}"
          namespace: vault-admin
        spec:
          authentication: 
            path: ${CLUSTER_NAME}
            role: vault-admin
          path: /infra/clusters/${CLUSTER_NAME}/jwt
          serviceAccountName: "{{ .Name }}-tenant-gitops"
          allowedKubernetesNamespaces: 
          - vault-admin
      excludedPaths:	
        - .spec.replicas	
        - .metadata	
        - .status