apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster-ingress-certificate.yaml
  - ./ingress-controller-patch.yaml
  - ./letsencrypt-issuer.yaml
  - ./patches-rbac.yaml
  - ./patches.yaml
  - ./cert-manager-patch.yaml
  - ./cluster-api-certificate.yaml
  - ./api-cert-patch.yaml