applications:

  namespace-configurations:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: namespace-configuration-operator
    source:
      path: groups/multi-tenant/overlays/namespace-configurations   

  cert-manager-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: cert-manager-operator
    source:
      path: components/cert-manager-operator 

  cert-manager-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: cert-manager
    source:
      path: groups/multi-tenant/overlays/cert-manager-configuration
    extraFields: |
      ignoreDifferences:
        - group: 'cert-manager.io'
          jsonPointers:
            - /spec/acme/solvers
          kind: ClusterIssuer        

  group-sync-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: group-sync-configuration
    source:
      path: groups/multi-tenant/overlays/group-sync-configuration

  oauth-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-config  
    source:
      path: components/oauth-config

  vault-admin:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: vault-admin  
    source:
      path: groups/multi-tenant/overlays/vault-admin      

  approved-namespaces-app:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: default
    source:
      path: components/approved-namespaces-app

  kube-ops-view:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: kube-ops-view
    source:
      path: components/kube-ops-view      

  vault-sidecar-injection:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: vault
    source:
      path: groups/multi-tenant/overlays/vault-sidecar-injection

  crossplane-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '8'
    destination:
      namespace: crossplane-system
    source:
      path: components/crossplane-operator
    extraFields: |
      ignoreDifferences:
        - group: 'apps'
          jsonPointers:
            - /spec/template/spec/containers/0/env/0/valueFrom/resourceFieldRef/divisor
            - /spec/template/spec/containers/0/env/1/valueFrom/resourceFieldRef/divisor
            - /spec/template/spec/initContainers/0/env/0/valueFrom/resourceFieldRef/divisor
            - /spec/template/spec/initContainers/0/env/1/valueFrom/resourceFieldRef/divisor            
          kind: Deployment            

  crossplane-providers:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: crossplane-system
    source:
      path: components/crossplane-providers

  crossplane-provider-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: crossplane-system
    source:
      path: components/crossplane-provider-config

  crossplane-compositions:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: crossplane-system
    source:
      path: components/crossplane-compositions 

  crossplane-vault:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '7'
    destination:
      namespace: vault-admin
    source:
      path: components/crossplane-vault                      


     