apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: group-sync-operator
resources:
  - ../../../../components/group-sync-configuration/

patches:

- patch: |-
    - op: replace
      path: /spec/providers/0/keycloak/url
      value: "https://keycloak-sso.apps.${HUB_BASE_DOMAIN}/auth"
  target:
    kind: GroupSync
    name: keycloak
    namespace: group-sync-operator